name: Build and publish

on: 
  workflow_dispatch:

permissions:
  contents: read
  pages: write
  id-token: write

concurrency:
  group: "pages"
  cancel-in-progress: false

jobs:
  build_pages:
    name:  Build HTML pages
    runs-on: ubuntu-latest
    env:
      ANT_OPTS: -Xmx5g

    steps:
      - name: Perform Checkout
        uses: actions/checkout@v7
      - name: set up uv (Python)
        uses: astral-sh/setup-uv@v8.1.0
      - name: Install system dependencies
        run: |
          sudo apt-get update
          sudo apt-get install -y libcairo2-dev pkg-config
      - name: Install Python dependencies
        run: |
          uv sync
          echo "$GITHUB_WORKSPACE/.venv/bin" >> $GITHUB_PATH
      - name: Fetch data
        run: ./shellscripts/fetch_data.sh
      - name: Fix broken XML
        run: ./shellscripts/mendxml.sh
      - name: Generate initals indices
        run: pyscripts/get_initials.py
      - name: Generate Imprint
        run: ./shellscripts/dl_imprint.sh
      - name: Build
        run: ant
      - name: Update Favicons
        run: ./pyscripts/update_favicons.py
      - name: Update Translations
        run: ./pyscripts/make_translations.py
      - name: Upload artifact
        uses: actions/upload-pages-artifact@v5
        with:
          github_token: ${{secrets.GITHUB_TOKEN}}
          path: './html'
  deploy_pages:
    runs-on: ubuntu-latest
    needs: build_pages
    environment:
      name: github-pages
    steps:
      - uses: actions/deploy-pages@v5
